import { Brand, AmbassadorLevel, AmbassadorProgram, AmbassadorTask, AmbassadorApplication, AmbassadorProfile, AmbassadorStats, TaskSubmission } from '../types/ambassador';

export const mockBrands: Brand[] = [
  {
    id: 'brand-1',
    name: 'L\'Oréal Paris',
    description: 'Dünya\'nın en büyük güzellik markalarından biri. Cilt bakımı, makyaj ve saç bakımı ürünleri ile kadınların güzelliğini ortaya çıkarıyor.',
    logoUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=200&h=200&fit=crop',
    websiteUrl: 'https://www.lorealparis.com.tr',
    industry: 'beauty',
    briefVideoUrl: 'https://example.com/loreal-brief.mp4',
    detailedBrief: 'L\'Oréal Paris olarak, güzellik tutkunu influencerlar ile çalışarak markamızın değerlerini ve ürünlerimizi hedef kitlemize ulaştırmayı hedefliyoruz. Elçilerimizden beklediğimiz: 1) Ürünlerimizi doğal ve samimi bir şekilde tanıtmaları 2) Kendi güzellik rutinlerinde markamızı entegre etmeleri 3) Takipçileriyle güzellik ipuçlarını paylaşmaları 4) Marka değerlerimizi yansıtan içerik üretmeleri',
    requirements: ['En az 10.000 takipçiye sahip olmak', 'Güzellik içerikleri üretmek', 'Profesyonel fotoğraf çekimleri yapabilmek'],
    benefits: ['Ücretsiz ürün gönderimi', 'Yüksek komisyon oranları', 'Marka etkinliklerine davet', 'Özel indirimler'],
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'brand-4',
    name: 'Qora Science Camp',
    description: 'Meraklı çocuklar için bilim ve doğanın buluştuğu yer. Bilim deneyleri, doğa keşifleri, robotik & teknoloji, yaratıcı sanat atölyeleri ve ekoloji projeleri ile dolu unutulmaz bir deneyim.',
    logoUrl: 'https://framerusercontent.com/images/lQdRYkpuhhFIGjHmJs1dYqg2mk0.jpeg?scale-down-to=1024',
    websiteUrl: 'https://www.qorasciencecamp.com',
    industry: 'education',
    briefVideoUrl: 'https://example.com/qora-brief.mp4',
    detailedBrief: 'Qora Science Camp olarak, aile odaklı içerik üreten influencerlar ile çalışarak çocukların merak duygusunu tetiklemeyi ve bilim & doğayla bağ kurmasını sağlamayı hedefliyoruz. Elçilerimizden beklediğimiz: 1) Çocuklarıyla birlikte kamptaki etkinlikleri paylaşmaları 2) Eğlenceli ve eğitici içerikler üretmeleri 3) Bilim ve doğa sevgisini yaymaları 4) Aile değerlerini ön plana çıkarmaları',
    requirements: ['En az 5.000 takipçiye sahip olmak', 'Aile/ebeveyn odaklı içerik üretmek', 'Çocuklarla etkileşimli içerikler yapabilmek'],
    benefits: ['Ücretsiz kamp deneyimi', 'Yüksek komisyon oranları', 'Özel aile etkinliklerine davet', 'Eğitici materyal desteği'],
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'brand-2',
    name: 'Nike',
    description: 'Just Do It sloganı ile spor ve yaşam tarzı alanında lider marka. Spor ayakkabıları, giyim ve ekipmanları ile performans ve stil sunuyor.',
    logoUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    websiteUrl: 'https://www.nike.com',
    industry: 'sports',
    briefVideoUrl: 'https://example.com/nike-brief.mp4',
    detailedBrief: 'Nike olarak, spor tutkunu ve aktif yaşam tarzını benimseyen influencerlar ile çalışarak "Just Do It" ruhunu yaymayı hedefliyoruz. Elçilerimizden beklediğimiz: 1) Spor aktivitelerinde Nike ürünlerini kullanmaları 2) Motivasyonel içerikler üretmeleri 3) Fitness ve sağlıklı yaşam ipuçları paylaşmaları 4) Spor etkinliklerinde markamızı temsil etmeleri',
    requirements: ['En az 15.000 takipçiye sahip olmak', 'Spor içerikleri üretmek', 'Aktif yaşam tarzına sahip olmak'],
    benefits: ['Yeni ürün öncelikli erişim', 'Spor etkinliklerine davet', 'Yüksek komisyon oranları', 'Özel koleksiyonlara erişim'],
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'brand-3',
    name: 'Apple',
    description: 'Teknoloji dünyasının öncü markası. iPhone, iPad, Mac ve diğer yenilikçi ürünleri ile hayatı kolaylaştırıyor.',
    logoUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=200&h=200&fit=crop',
    websiteUrl: 'https://www.apple.com',
    industry: 'technology',
    briefVideoUrl: 'https://example.com/apple-brief.mp4',
    detailedBrief: 'Apple olarak, teknoloji tutkunu ve yaratıcı influencerlar ile çalışarak ürünlerimizin potansiyelini göstermeyi hedefliyoruz. Elçilerimizden beklediğimiz: 1) Apple ekosistemini etkili kullanmaları 2) Yaratıcı içerikler üretmeleri 3) Teknoloji trendlerini takip etmeleri 4) Ürün özelliklerini doğru şekilde tanıtmaları',
    requirements: ['En az 20.000 takipçiye sahip olmak', 'Teknoloji içerikleri üretmek', 'Apple ürünlerini kullanmak'],
    benefits: ['Yeni ürün öncelikli erişim', 'Apple Store etkinlikleri', 'Yüksek komisyon oranları', 'Teknik destek'],
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockAmbassadorLevels: AmbassadorLevel[] = [
  {
    id: 'level-1',
    level: 1,
    name: 'Bronze Elçi',
    description: 'Yeni başlayan elçi seviyesi',
    minTasksCompleted: 0,
    minEarnings: 0,
    benefits: ['Temel görevlere erişim', 'Marka brief\'lerine erişim'],
    badgeIcon: '🥉',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'level-2',
    level: 2,
    name: 'Silver Elçi',
    description: 'Deneyimli elçi seviyesi',
    minTasksCompleted: 5,
    minEarnings: 1000,
    benefits: ['Özel görevlere erişim', 'Yüksek komisyon oranları'],
    badgeIcon: '🥈',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'level-3',
    level: 3,
    name: 'Gold Elçi',
    description: 'Uzman elçi seviyesi',
    minTasksCompleted: 15,
    minEarnings: 5000,
    benefits: ['VIP görevlere erişim', 'Öncelikli destek'],
    badgeIcon: '🥇',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'level-4',
    level: 4,
    name: 'Platinum Elçi',
    description: 'Premium elçi seviyesi',
    minTasksCompleted: 30,
    minEarnings: 15000,
    benefits: ['Exclusive görevlere erişim', 'Kişisel marka danışmanı'],
    badgeIcon: '💎',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'level-5',
    level: 5,
    name: 'Diamond Elçi',
    description: 'Elite elçi seviyesi',
    minTasksCompleted: 50,
    minEarnings: 30000,
    benefits: ['Tüm görevlere erişim', 'Özel etkinlikler', 'Marka ortaklıkları'],
    badgeIcon: '👑',
    createdAt: new Date('2024-01-01'),
  },
];

export const mockAmbassadorPrograms: AmbassadorProgram[] = [
  {
    id: 'program-1',
    brandId: 'brand-1',
    title: 'L\'Oréal Paris Güzellik Elçisi',
    description: 'L\'Oréal Paris markasının güzellik elçisi olarak görev yapacak influencerlar arıyoruz.',
    requirements: ['Güzellik içerikleri üretmek', 'Haftada en az 2 içerik paylaşmak', 'Marka değerlerini yansıtmak'],
    benefits: ['Ücretsiz ürün gönderimi', 'Yüksek komisyon oranları', 'Marka etkinliklerine davet'],
    commissionRate: 15.00,
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    brand: mockBrands[0],
  },
  {
    id: 'program-4',
    brandId: 'brand-4',
    title: 'Qora Science Camp Aile Elçisi',
    description: 'Qora Science Camp\'in aile elçisi olarak görev yapacak influencerlar arıyoruz.',
    requirements: ['Aile odaklı içerikler üretmek', 'Çocuklarla etkileşimli içerikler yapmak', 'Bilim ve doğa sevgisini yaymak'],
    benefits: ['Ücretsiz kamp deneyimi', 'Yüksek komisyon oranları', 'Özel aile etkinliklerine davet'],
    commissionRate: 18.00,
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    brand: mockBrands[3],
  },
  {
    id: 'program-2',
    brandId: 'brand-2',
    title: 'Nike Spor Elçisi',
    description: 'Nike markasının spor elçisi olarak görev yapacak influencerlar arıyoruz.',
    requirements: ['Spor içerikleri üretmek', 'Aktif yaşam tarzını yansıtmak', 'Motivasyonel içerikler paylaşmak'],
    benefits: ['Yeni ürün öncelikli erişim', 'Spor etkinliklerine davet', 'Yüksek komisyon oranları'],
    commissionRate: 20.00,
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    brand: mockBrands[1],
  },
  {
    id: 'program-3',
    brandId: 'brand-3',
    title: 'Apple Teknoloji Elçisi',
    description: 'Apple markasının teknoloji elçisi olarak görev yapacak influencerlar arıyoruz.',
    requirements: ['Teknoloji içerikleri üretmek', 'Apple ekosistemini kullanmak', 'Yaratıcı içerikler üretmek'],
    benefits: ['Yeni ürün öncelikli erişim', 'Apple Store etkinlikleri', 'Yüksek komisyon oranları'],
    commissionRate: 25.00,
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    brand: mockBrands[2],
  },
];

export const mockAmbassadorTasks: AmbassadorTask[] = [
  {
    id: 'task-qora-1',
    programId: 'program-4',
    title: 'Qora Kamp Deneyimi Paylaşımı',
    description: 'Qora Science Camp\'te çocuğunuzla birlikte yaşadığınız deneyimi paylaşan bir video içerik oluşturun.',
    taskType: 'content_creation',
    requirements: ['En az 2 dakika video', 'Kamp atmosferini yansıtma', 'Çocuklarla etkileşim gösterme'],
    deliverables: ['Instagram Reels video', 'TikTok video', 'YouTube Shorts'],
    rewardAmount: 600.00,
    rewardCurrency: '₺',
    deadlineDays: 5,
    priority: 'high',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    program: mockAmbassadorPrograms[3],
    submissions: [],
    completionPercentage: 75, // Sample data to show progress
  },
  {
    id: 'task-qora-2',
    programId: 'program-4',
    title: 'Bilim Deneyi İçeriği',
    description: 'Qora\'da öğrendiğiniz bilim deneylerinden birini evde tekrarlayarak eğitici bir içerik hazırlayın.',
    taskType: 'content_creation',
    requirements: ['Deney sürecini gösterme', 'Güvenlik kurallarına uyma', 'Eğitici açıklamalar ekleme'],
    deliverables: ['Instagram Post', 'Instagram Story serisi', 'TikTok video'],
    rewardAmount: 400.00,
    rewardCurrency: '₺',
    deadlineDays: 7,
    priority: 'normal',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    program: mockAmbassadorPrograms[3],
    submissions: [],
    completionPercentage: 0,
  },
  {
    id: 'task-qora-3',
    programId: 'program-4',
    title: 'Doğa Keşfi Vlog',
    description: 'Qora\'nın doğa keşif etkinliklerini içeren bir vlog hazırlayın.',
    taskType: 'content_creation',
    requirements: ['Doğa güzelliklerini vurgulama', 'Çevre bilinci mesajı verme', 'Aile etkileşimini gösterme'],
    deliverables: ['YouTube video', 'Instagram Reels', 'Blog post'],
    rewardAmount: 500.00,
    rewardCurrency: '₺',
    deadlineDays: 10,
    priority: 'normal',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    program: mockAmbassadorPrograms[3],
    submissions: [],
    completionPercentage: 0,
  },
  {
    id: 'task-1',
    programId: 'program-1',
    title: 'L\'Oréal Ürün Tanıtımı',
    description: 'L\'Oréal Paris\'in yeni cilt bakım ürününü tanıtan bir video içerik oluşturun.',
    taskType: 'content_creation',
    requirements: ['En az 60 saniye video', 'Ürün özelliklerini vurgulama', 'Doğal ve samimi ton'],
    deliverables: ['Instagram Reels video', 'YouTube Shorts video', 'TikTok video'],
    rewardAmount: 500.00,
    rewardCurrency: '₺',
    deadlineDays: 7,
    priority: 'normal',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    program: mockAmbassadorPrograms[0],
    submissions: [],
    completionPercentage: 33, // Sample data to show progress
  },
  {
    id: 'task-2',
    programId: 'program-1',
    title: 'Güzellik Rutini Paylaşımı',
    description: 'Günlük güzellik rutininizde L\'Oréal ürünlerini kullanarak bir paylaşım yapın.',
    taskType: 'social_media',
    requirements: ['En az 3 ürün kullanımı', 'Rutin açıklaması', 'Hashtag kullanımı'],
    deliverables: ['Instagram post', 'Instagram story'],
    rewardAmount: 300.00,
    rewardCurrency: '₺',
    deadlineDays: 3,
    priority: 'normal',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    program: mockAmbassadorPrograms[0],
    submissions: [],
    completionPercentage: 100, // Sample data to show completed state
  },
  {
    id: 'task-3',
    programId: 'program-2',
    title: 'Nike Spor Ayakkabı Testi',
    description: 'Nike\'ın yeni spor ayakkabısını test ederek bir değerlendirme videosu çekin.',
    taskType: 'product_review',
    requirements: ['En az 3 dakika video', 'Performans testi', 'Konfor değerlendirmesi'],
    deliverables: ['YouTube video', 'Instagram Reels'],
    rewardAmount: 800.00,
    rewardCurrency: '₺',
    deadlineDays: 10,
    priority: 'high',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    program: mockAmbassadorPrograms[1],
    submissions: [],
    completionPercentage: 0,
  },
  {
    id: 'task-4',
    programId: 'program-2',
    title: 'Fitness Motivasyonu',
    description: 'Nike ürünleri ile fitness antrenmanınızı paylaşın ve takipçilerinizi motive edin.',
    taskType: 'content_creation',
    requirements: ['En az 2 dakika video', 'Motivasyonel mesaj', 'Nike ürün kullanımı'],
    deliverables: ['Instagram Reels', 'TikTok video'],
    rewardAmount: 400.00,
    rewardCurrency: '₺',
    deadlineDays: 5,
    priority: 'normal',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    program: mockAmbassadorPrograms[1],
    submissions: [],
    completionPercentage: 0,
  },
  {
    id: 'task-5',
    programId: 'program-3',
    title: 'iPhone Özellik Tanıtımı',
    description: 'iPhone\'un yeni özelliklerini tanıtan yaratıcı bir içerik oluşturun.',
    taskType: 'content_creation',
    requirements: ['En az 2 dakika video', 'Özellik açıklaması', 'Yaratıcı yaklaşım'],
    deliverables: ['YouTube video', 'Instagram Reels'],
    rewardAmount: 600.00,
    rewardCurrency: '₺',
    deadlineDays: 7,
    priority: 'normal',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    program: mockAmbassadorPrograms[2],
    submissions: [],
    completionPercentage: 0,
  },
  {
    id: 'task-6',
    programId: 'program-3',
    title: 'MacBook Kullanım Rehberi',
    description: 'MacBook kullanımı ile ilgili faydalı ipuçları içeren bir rehber hazırlayın.',
    taskType: 'content_creation',
    requirements: ['En az 5 dakika video', 'Pratik ipuçları', 'Ekran kaydı'],
    deliverables: ['YouTube video', 'Blog post'],
    rewardAmount: 700.00,
    rewardCurrency: '₺',
    deadlineDays: 14,
    priority: 'normal',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    program: mockAmbassadorPrograms[2],
    submissions: [],
    completionPercentage: 0,
  },
];

export const mockAmbassadorApplications: AmbassadorApplication[] = [
  {
    id: 'app-1',
    userId: '1',
    programId: 'program-1',
    status: 'accepted',
    motivationText: 'Güzellik tutkunu biriyim ve L\'Oréal ile çalışmak benim için büyük bir fırsat. Markanın değerlerini yansıtan içerikler üretmek istiyorum.',
    experienceText: '2 yıldır güzellik içerikleri üretiyorum. Instagram ve TikTok\'ta toplam 25K takipçim var.',
    portfolioLinks: ['https://instagram.com/beautycontent', 'https://tiktok.com/@beautycontent'],
    appliedAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
    program: mockAmbassadorPrograms[0],
  },
  {
    id: 'app-2',
    userId: '1',
    programId: 'program-2',
    status: 'pending',
    motivationText: 'Spor ve fitness hayatımın vazgeçilmez bir parçası. Nike ile çalışarak motivasyonel içerikler üretmek istiyorum.',
    experienceText: 'Fitness eğitmeniyim ve sosyal medyada spor içerikleri paylaşıyorum.',
    portfolioLinks: ['https://instagram.com/fitnesscoach', 'https://youtube.com/fitnesscoach'],
    appliedAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
    program: mockAmbassadorPrograms[1],
  },
];

export const mockAmbassadorProfile: AmbassadorProfile = {
  id: 'profile-1',
  userId: '1',
  levelId: 'level-2',
  currentLevel: 2,
  totalTasksCompleted: 8,
  totalEarnings: 3200.00,
  activePrograms: 2,
  badges: ['🥉', '🥈', '⭐'],
  bio: 'Güzellik ve yaşam tarzı içerik üreticisi. Markalarla işbirliği yaparak kaliteli içerikler üretiyorum.',
  specialties: ['Güzellik', 'Yaşam Tarzı', 'Fitness'],
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-25'),
  level: mockAmbassadorLevels[1],
};

export const mockAmbassadorStats: AmbassadorStats = {
  totalTasks: 12,
  completedTasks: 8,
  totalEarnings: 3200.00,
  currentLevel: 2,
  nextLevelProgress: 60, // 8/15 tasks completed for level 3
  activePrograms: 2,
  badges: ['🥉', '🥈', '⭐'],
};


