import { Campaign, User, Application, Invitation, Notification } from '../types';

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    title: '🛰️✨ Quantum Orbit Labs – Bilim & Teknoloji Savunucuları Kampanyası',
    description: 'Quantum Orbit Labs, kuantum nokta sensörleri ve ileri görüntüleme malzemeleri ile teknolojinin sınırlarını zorluyor. Amacımız: Influencer\'ların yaratacağı içeriklerle kuantum teknolojilerinin günlük yaşam ve endüstrideki önemini anlatmak ve marka bilinirliğini artırmak.',
    brand: 'Quantum Orbit Labs',
    budget: 35000,
    budgetCurrency: '₺',
    platforms: ['instagram', 'tiktok', 'youtube', 'linkedin'],
    category: 'technology',
    requirements: [
      'Min. 5K takipçi, teknoloji / mühendislik / bilim iletişimi yapan influencer',
      'Instagram Reel / TikTok → "Kuantum teknolojileri geleceğimizi nasıl değiştiriyor?" temalı kısa video',
      'YouTube (Opsiyonel) → Quantum Orbit Labs\'in geliştirdiği sensörlerin kullanım alanlarını anlatan içerik',
      'LinkedIn / Blog Post → "Quantum Orbit Labs ile geleceğin görüntüleme teknolojileri" başlıklı profesyonel paylaşım',
      '#FutureInSight hashtag\'i ile tüm paylaşımların etkileşimini toplamak'
    ],
    exampleContent: [
      '"Kuantum teknolojileri geleceğimizi nasıl değiştiriyor?" temalı kısa video',
      'Quantum Orbit Labs\'in geliştirdiği sensörlerin kullanım alanlarını (otomotiv, robotik, sağlık) anlatan içerik',
      '"Quantum Orbit Labs ile geleceğin görüntüleme teknolojileri" başlıklı profesyonel paylaşım',
      'Kuantum teknolojilerinin günlük yaşam ve endüstrideki uygulamaları'
    ],
    minFollowers: 5000,
    deadline: new Date('2025-09-15'),
    status: 'active',
    isSpecialInvitation: true,
    imageUrl: 'https://quantumorbitlabs.com/wp-content/uploads/2024/08/agrotech-agroalimentario-arquime.jpg',
    createdAt: new Date('2025-01-27'),
    updatedAt: new Date('2025-01-27'),
  },
  {
    id: '2',
    title: '🍨✨ TooA Milano PRO – Lansman Kampanyası',
    description: 'TooA Milano PRO ile evde dakikalar içinde gerçek İtalyan dondurması yap! Kişiselleştirilebilir kıvam ayarları, uygulama bağımsız kullanım kolaylığı ve %100 Made in Italy kalitesiyle TooA artık Türkiye\'de. 💡 Hedefimiz: Influencer\'ların içerikleriyle "evde İtalyan dondurma keyfi" konseptini yaymak ve marka bilinirliğini artırmak.',
    brand: 'TooA Milano PRO',
    budget: 50000,
    budgetCurrency: '₺',
    platforms: ['instagram', 'tiktok', 'youtube'],
    category: 'food',
    requirements: [
      'Min. 10K takipçi, lifestyle / food / family içerik üreten influencer',
      'Instagram Reel / TikTok → "Evde kendi İtalyan dondurmamı yaptım!" temalı kısa video',
      'Instagram Post → TooA Milano PRO ile hazırlanan özel tatlı/kokteyl paylaşımı',
      'Story Serisi → Cihazın kolay kullanımı ve farklı kıvam seçenekleri anlatımı',
      'Blog / YouTube (Opsiyonel) → "Evde profesyonel dondurma deneyimi" incelemesi'
    ],
    exampleContent: [
      '"Evde kendi İtalyan dondurmamı yaptım!" temalı kısa video',
      'TooA Milano PRO ile hazırlanan özel tatlı/kokteyl paylaşımı',
      'Cihazın kolay kullanımı ve farklı kıvam seçenekleri anlatımı',
      '"Evde profesyonel dondurma deneyimi" incelemesi'
    ],
    minFollowers: 10000,
    deadline: new Date('2025-09-10'),
    status: 'active',
    isSpecialInvitation: true,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0556/1244/0919/files/Italian_ice_cream_2.png?v=1751453419',
    createdAt: new Date('2025-01-26'),
    updatedAt: new Date('2025-01-26'),
  },
  {
    id: '3',
    title: '🌿✨ Qora – Bilim & Doğa Kampı Kampanyası',
    description: '🚀 Meraklı Çocuklar İçin Bilim ve Doğanın Buluştuğu Yer! Qora\'da çocuklar bilim deneyleri 🔬, doğa keşifleri 🌲, robotik & teknoloji 🤖, yaratıcı sanat atölyeleri 🎨 ve ekoloji projeleri ♻️ ile dolu unutulmaz bir deneyim yaşıyor. 💡 Amacımız: Çocukların merak duygusunu tetiklemek, bilim & doğayla bağ kurmasını sağlamak ve yarının mucitlerini yetiştirmek.',
    brand: 'Qora Science Camp',
    budget: 20000,
    budgetCurrency: '₺',
    platforms: ['instagram', 'tiktok'],
    category: 'lifestyle',
    requirements: [
      'Min. 5K takipçi, aile/ebeveyn odaklı içerik üreten influencer',
      'Instagram Post + Reel → Çocuğunuzla kamptaki bir etkinliği paylaşın',
      'TikTok Video → "Bir Gün Qora Kampında" konseptiyle eğlenceli vlog',
      'Blog / Story Serisi → "Qora\'da Öğrendiklerimiz" başlığıyla deneyimi aktarın',
      '#QoraScienceCamp hashtag\'iyle paylaşımlar → WOM etkisini artırmak'
    ],
    exampleContent: [
      'Fizik Deneyi 🔭, Orman Yürüyüşü 🌳, Robotik Çalışma 🤖 etkinlikleri',
      '"Bir Gün Qora Kampında" konseptiyle eğlenceli vlog',
      '"Qora\'da Öğrendiklerimiz" başlığıyla deneyim aktarımı',
      'Kamp atmosferini yansıtan aile içerikleri'
    ],
    minFollowers: 5000,
    deadline: new Date('2025-09-05'),
    status: 'active',
    isSpecialInvitation: true,
    imageUrl: 'https://framerusercontent.com/images/lQdRYkpuhhFIGjHmJs1dYqg2mk0.jpeg?scale-down-to=1024',
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-01-25'),
  },
  {
    id: '4',
    title: '#TeamWater Farkındalık Kampanyası',
    description: 'Su kıtlığı ve temiz su erişimi konusunda farkındalık yaratmayı amaçlayan global kampanya. YouTube içerik üreticileri ile işbirliği yaparak dünya çapında 6 milyondan fazla kişiye temiz su sağlamayı hedefliyoruz.',
    brand: 'MrBeast & Mark Rober',
    creators: ['MrBeast', 'Mark Rober'],
    budget: 40000,
    budgetCurrency: '₺',
    platforms: ['youtube', 'instagram', 'tiktok'],
    category: 'lifestyle',
    requirements: [
      'En az 5.000 takipçiye sahip olmak',
      'Su tasarrufu ve temiz su konularında içerik üretmeye istekli olmak',
      'Kampanya süresince en az 3 içerik paylaşmak',
      'İçeriklerde #TeamWater etiketini kullanmak',
      'Kampanya sonuçlarını takipçilerinizle paylaşmak'
    ],
    exampleContent: [
      'Su tasarrufu için pratik ipuçları içeren video',
      'Temiz su erişimi olmayan bölgeler hakkında bilgilendirici içerik',
      'Su kirliliğinin etkilerini gösteren deneyler',
      'Günlük hayatta su tüketimini azaltma yolları'
    ],
    minFollowers: 5000,
    deadline: new Date('2025-12-15'),
    status: 'active',
    isSpecialInvitation: true,
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=300&fit=crop',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '5',
    title: 'Revolve @ Coachella',
    description: 'Coachella festivalinde Revolve markasını temsil edecek influencerlar arıyoruz. Festival atmosferini yansıtan içerikler ve marka entegrasyonu.',
    brand: 'Revolve',
    budget: 15000,
    budgetCurrency: '₺',
    platforms: ['instagram', 'tiktok'],
    category: 'fashion',
    requirements: [
      'En az 20.000 takipçiye sahip olmak',
      'Moda ve yaşam tarzı içerik üretmek',
      'Festival atmosferini yansıtan içerikler',
      'Revolve ürünlerini doğal şekilde entegre etmek'
    ],
    exampleContent: [
      'Festival outfit videoları',
      'Revolve ürünlerinin günlük kullanımı',
      'Festival hazırlık süreci',
      'Backstage içerikler'
    ],
    minFollowers: 20000,
    deadline: new Date('2025-03-20'),
    status: 'active',
    isSpecialInvitation: false,
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&h=300&fit=crop',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: '6',
    title: 'L\'Oréal x Urban Decay',
    description: 'Urban Decay koleksiyonunu tanıtacak güzellik influencerları arıyoruz. Yaratıcı makyaj içerikleri ve ürün değerlendirmeleri.',
    brand: 'L\'Oréal',
    budget: 8000,
    budgetCurrency: '₺',
    platforms: ['instagram', 'tiktok'],
    category: 'beauty',
    requirements: [
      'En az 10.000 takipçiye sahip olmak',
      'Güzellik ve makyaj içerik üretmek',
      'Urban Decay ürünlerini kullanarak yaratıcı makyajlar',
      'Ürün değerlendirme videoları'
    ],
    exampleContent: [
      'Urban Decay ile yaratıcı makyaj tutorialları',
      'Ürün değerlendirme videoları',
      'Günlük makyaj rutinleri',
      'Özel etkinlik makyajları'
    ],
    minFollowers: 10000,
    deadline: new Date('2025-05-10'),
    status: 'active',
    isSpecialInvitation: false,
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-02-01'),
  },
  {
    id: '7',
    title: 'Daadi Snacks \'De-influencer\' Kampanyası',
    description: 'De-influencer trendini kullanarak atıştırmalık ürünlerimizi tanıtacak yaratıcı içerik üreticileri arıyoruz.',
    brand: 'Daadi Snacks',
    budget: 3000,
    budgetCurrency: '₺',
    platforms: ['tiktok', 'instagram'],
    category: 'food',
    requirements: [
      'En az 5.000 takipçiye sahip olmak',
      'De-influencer tarzında içerik üretmek',
      'Ürünleri doğal şekilde entegre etmek',
      'Eğlenceli ve yaratıcı içerikler'
    ],
    exampleContent: [
      'De-influencer tarzında ürün tanıtımları',
      'Atıştırmalık karşılaştırma videoları',
      'Eğlenceli ürün testleri',
      'Günlük atıştırmalık rutinleri'
    ],
    minFollowers: 5000,
    deadline: new Date('2025-06-30'),
    status: 'active',
    isSpecialInvitation: false,
    imageUrl: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=400&h=300&fit=crop',
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-02-15'),
  },
  {
    id: '8',
    title: 'Samsung Olimpiyat Kampanyası',
    description: 'Paris 2024 Olimpiyatları için Samsung ürünlerini tanıtacak özel davetli influencerlar arıyoruz.',
    brand: 'Samsung',
    budget: 25000,
    budgetCurrency: '₺',
    platforms: ['instagram', 'youtube', 'tiktok'],
    category: 'technology',
    requirements: [
      'En az 50.000 takipçiye sahip olmak',
      'Teknoloji içerik üretmek',
      'Olimpiyat temasını kullanmak',
      'Samsung ürünlerini doğal şekilde entegre etmek'
    ],
    exampleContent: [
      'Samsung ürünleri ile Olimpiyat içerikleri',
      'Teknoloji ve spor entegrasyonu',
      'Olimpiyat hazırlık süreçleri',
      'Samsung ürün değerlendirmeleri'
    ],
    minFollowers: 50000,
    deadline: new Date('2024-07-01'),
    status: 'active',
    isSpecialInvitation: true,
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: '9',
    title: 'Calvin Klein x Yaz Koleksiyonu',
    description: 'Calvin Klein yaz koleksiyonunu tanıtacak moda influencerları arıyoruz. Minimalist ve şık içerikler.',
    brand: 'Calvin Klein',
    budget: 12000,
    budgetCurrency: '₺',
    platforms: ['instagram', 'tiktok'],
    category: 'fashion',
    requirements: [
      'En az 30.000 takipçiye sahip olmak',
      'Moda ve yaşam tarzı içerik üretmek',
      'Minimalist ve şık içerikler',
      'Calvin Klein estetiğini yansıtmak'
    ],
    exampleContent: [
      'Yaz koleksiyonu lookbook videoları',
      'Günlük outfit kombinleri',
      'Minimalist moda içerikleri',
      'Calvin Klein estetiği ile fotoğraflar'
    ],
    minFollowers: 30000,
    deadline: new Date('2025-04-15'),
    status: 'active',
    isSpecialInvitation: false,
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-01-20'),
  },
];

export const mockUser: User = {
  id: '1',
  email: 'ahmet.yilmaz@example.com',
  firstName: 'Ahmet',
  lastName: 'Yılmaz',
  profileImage: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=200&h=200&fit=crop&crop=faces',
  bio: 'Moda ve yaşam tarzı içerik üreticisi. İstanbul merkezli. Markalarla işbirliği için DM atabilirsiniz.',
  socialMedia: {
    instagram: {
      username: '@ahmetyilmaz',
      followers: 5000,
      verified: false,
    },
    tiktok: {
      username: '@ahmetyilmaz',
      followers: 10000,
      verified: false,
    },
    youtube: {
      channelId: 'UC123456789',
      subscribers: 2000,
      verified: false,
    },
  },
  followerCount: 17000,
  contentCategories: ['Moda', 'Yaşam Tarzı', 'Seyahat'],
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2025-01-01'),
};

export const mockApplications: Application[] = [
  {
    id: '1',
    userId: '1',
    campaignId: '4',
    status: 'pending',
    personalMessage: 'Su tasarrufu konusunda çok duyarlıyım ve bu kampanyada yer almak istiyorum.',
    appliedAt: new Date('2025-05-15'),
    updatedAt: new Date('2025-05-15'),
    campaign: mockCampaigns[3],
  },
  {
    id: '2',
    userId: '1',
    campaignId: '5',
    status: 'accepted',
    personalMessage: 'Festival atmosferini çok seviyorum ve Revolve ile çalışmak harika olur.',
    appliedAt: new Date('2025-03-05'),
    updatedAt: new Date('2025-03-10'),
    campaign: mockCampaigns[4],
  },
  {
    id: '3',
    userId: '1',
    campaignId: '6',
    status: 'rejected',
    personalMessage: 'Güzellik içerikleri üretiyorum ve Urban Decay ile çalışmak istiyorum.',
    appliedAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-02-25'),
    campaign: mockCampaigns[5],
  },
  {
    id: '4',
    userId: '1',
    campaignId: '7',
    status: 'completed',
    personalMessage: 'De-influencer tarzında içerikler üretiyorum ve bu kampanya çok ilgimi çekti.',
    appliedAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-30'),
    campaign: mockCampaigns[6],
  },
];

export const mockInvitations: Invitation[] = [
  {
    id: '1',
    userId: '1',
    campaignId: '1',
    isSpecial: true,
    sentAt: new Date('2025-01-27'),
    expiresAt: new Date('2025-02-15'),
    campaign: mockCampaigns[0],
  },
  {
    id: '2',
    userId: '1',
    campaignId: '2',
    isSpecial: true,
    sentAt: new Date('2025-01-26'),
    expiresAt: new Date('2025-02-10'),
    campaign: mockCampaigns[1],
  },
  {
    id: '3',
    userId: '1',
    campaignId: '3',
    isSpecial: true,
    sentAt: new Date('2025-01-25'),
    expiresAt: new Date('2025-02-10'),
    campaign: mockCampaigns[2],
  },
  {
    id: '4',
    userId: '1',
    campaignId: '8',
    isSpecial: true,
    sentAt: new Date('2024-12-15'),
    expiresAt: new Date('2024-12-30'),
    campaign: mockCampaigns[7],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    type: 'new_invitation',
    title: '🛰️✨ Quantum Orbit Labs - Bilim & Teknoloji Daveti!',
    message: 'Kuantum teknolojilerinin geleceğini keşfedin! Innovation Kit hediye + 35.000₺ bütçe!',
    isRead: false,
    createdAt: new Date('2025-01-27T10:00:00'),
    data: {
      campaignId: '1',
      invitationId: '1',
    },
  },
  {
    id: '2',
    userId: '1',
    type: 'new_invitation',
    title: '🍨✨ TooA Milano PRO - Özel Lansman Daveti!',
    message: 'Evde İtalyan dondurması yapma keyfi! TooA Milano PRO cihazı hediye + 50.000₺ bütçe!',
    isRead: false,
    createdAt: new Date('2025-01-26T10:00:00'),
    data: {
      campaignId: '2',
      invitationId: '2',
    },
  },
  {
    id: '3',
    userId: '1',
    type: 'new_invitation',
    title: '🌿✨ Qora Bilim & Doğa Kampı - Özel Davet!',
    message: 'Ailelere özel Qora Science Camp kampanyası için özel davet aldınız! Çocuğunuzla birlikte ücretsiz kampa katılma şansı!',
    isRead: false,
    createdAt: new Date('2025-01-25T09:00:00'),
    data: {
      campaignId: '3',
      invitationId: '3',
    },
  },
  {
    id: '4',
    userId: '1',
    type: 'application_accepted',
    title: 'Başvurunuz Kabul Edildi!',
    message: 'Revolve @ Coachella kampanyası için başvurunuz kabul edildi. Detayları görüntülemek için tıklayın.',
    isRead: false,
    createdAt: new Date('2025-01-15T10:30:00'),
    data: {
      campaignId: '5',
      applicationId: '2',
    },
  },
  {
    id: '5',
    userId: '1',
    type: 'new_invitation',
    title: 'Yeni Özel Davet',
    message: 'Samsung Olimpiyat Kampanyası için özel davet aldınız. Bu fırsatı kaçırmayın!',
    isRead: false,
    createdAt: new Date('2025-01-14T15:45:00'),
    data: {
      campaignId: '8',
      invitationId: '4',
    },
  },
  {
    id: '6',
    userId: '1',
    type: 'campaign_deadline',
    title: 'Kampanya Son Tarihi Yaklaşıyor',
    message: 'L\'Oréal x Urban Decay kampanyasının son başvuru tarihi 3 gün kaldı.',
    isRead: true,
    createdAt: new Date('2025-01-13T09:15:00'),
    data: {
      campaignId: '6',
    },
  },
  {
    id: '7',
    userId: '1',
    type: 'payment_received',
    title: 'Ödeme Alındı',
    message: 'Daadi Snacks kampanyası için 3.000 ₺ ödemeniz hesabınıza yatırıldı.',
    isRead: true,
    createdAt: new Date('2025-01-12T14:20:00'),
    data: {
      campaignId: '7',
      amount: 3000,
      currency: '₺',
    },
  },
  {
    id: '8',
    userId: '1',
    type: 'application_rejected',
    title: 'Başvuru Sonucu',
    message: 'L\'Oréal x Urban Decay kampanyası için başvurunuz reddedildi. Diğer fırsatları kaçırmayın!',
    isRead: true,
    createdAt: new Date('2025-01-11T11:30:00'),
    data: {
      campaignId: '6',
      applicationId: '3',
    },
  },
  {
    id: '9',
    userId: '1',
    type: 'new_campaign',
    title: 'Yeni Kampanya Eklendi',
    message: 'Sizin kategorinize uygun yeni bir kampanya eklendi: Calvin Klein x Yaz Koleksiyonu',
    isRead: true,
    createdAt: new Date('2025-01-10T16:00:00'),
    data: {
      campaignId: '9',
    },
  },
];
